# Generated by mini_c_compiler (Python equivalent)
# Note: ++/-- and assignment-as-expression are lowered into statements (no :=).

def main():
  a = 0
  i = 0
  while (i) < (1):
    print("hi")
    i += 1

if __name__ == "__main__":
  main()
