#pragma once

#include <cstdint>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>

#include "ast.h"

class PyGen {
public:
  std::string generate(const Program &p) {
    out_.str("");
    out_.clear();
    indent_ = 0;
    tmpCounter_ = 0;

    emitLine("# Generated by mini_c_compiler (Python equivalent)");
    emitLine("# Note: ++/-- and assignment-as-expression are lowered into statements (no :=).");
    emitLine("");
    emitLine("def main():");
    indent_++;

    for (const auto &s : p.stmts) genStmt(*s);

    indent_--;
    emitLine("");
    emitLine("if __name__ == \"__main__\":");
    indent_++;
    emitLine("main()");
    indent_--;
    return out_.str();
  }

private:
  void emitLine(const std::string &line) {
    for (int i = 0; i < indent_; i++) out_ << "  ";
    out_ << line << "\n";
  }

  std::string freshTmp() { return "_t" + std::to_string(tmpCounter_++); }

  static std::string pyStringLiteral(const std::string &s) {
    std::string r;
    r.reserve(s.size() + 2);
    r.push_back('"');
    for (char c : s) {
      switch (c) {
        case '\\': r += "\\\\"; break;
        case '"': r += "\\\""; break;
        case '\n': r += "\\n"; break;
        case '\t': r += "\\t"; break;
        case '\r': r += "\\r"; break;
        default: r.push_back(c); break;
      }
    }
    r.push_back('"');
    return r;
  }

  void genStmt(const Stmt &s) {
    if (const auto *b = dynamic_cast<const BlockStmt *>(&s)) {
      // Python doesn't need explicit braces; just emit statements.
      for (const auto &ss : b->stmts) genStmt(*ss);
      return;
    }
    if (const auto *d = dynamic_cast<const DeclStmt *>(&s)) {
      if (d->init) {
        std::string rhs = evalExpr(*d->init);
        emitLine(d->name + " = " + rhs);
      } else {
        emitLine(d->name + " = 0");
      }
      return;
    }
    if (const auto *es = dynamic_cast<const ExprStmt *>(&s)) {
      // Evaluate for side-effects; discard result.
      (void)evalExpr(*es->expr);
      return;
    }
    if (const auto *p = dynamic_cast<const PrintfStmt *>(&s)) {
      std::string v = evalExpr(*p->expr);
      emitLine("print(" + v + ")");
      return;
    }
    if (const auto *ps = dynamic_cast<const PrintfStrStmt *>(&s)) {
      emitLine("print(" + pyStringLiteral(ps->value) + ")");
      return;
    }
    if (const auto *ifs = dynamic_cast<const IfStmt *>(&s)) {
      std::string c = evalExpr(*ifs->cond);
      emitLine("if (" + c + ") != 0:");
      indent_++;
      genStmt(*ifs->thenS);
      if (blockWasEmpty(*ifs->thenS)) emitLine("pass");
      indent_--;
      if (ifs->elseS) {
        emitLine("else:");
        indent_++;
        genStmt(*ifs->elseS);
        if (blockWasEmpty(*ifs->elseS)) emitLine("pass");
        indent_--;
      }
      return;
    }
    if (const auto *ws = dynamic_cast<const WhileStmt *>(&s)) {
      std::string c = evalExpr(*ws->cond);
      emitLine("while (" + c + ") != 0:");
      indent_++;
      genStmt(*ws->body);
      if (blockWasEmpty(*ws->body)) emitLine("pass");
      indent_--;
      return;
    }
    if (const auto *fs = dynamic_cast<const ForStmt *>(&s)) {
      // Lower for(...) into init; while(cond){ body; post; }
      if (fs->init) genStmt(*fs->init);
      std::string cond = fs->cond ? evalExpr(*fs->cond) : "1";
      emitLine("while (" + cond + ") != 0:");
      indent_++;
      genStmt(*fs->body);
      if (fs->post) {
        // post is an expression (often i++/i-- or assignment)
        (void)evalExpr(*fs->post);
      }
      if (blockWasEmpty(*fs->body) && !fs->post) emitLine("pass");
      indent_--;
      return;
    }
    throw std::runtime_error("PyGen: unknown stmt node");
  }

  static bool blockWasEmpty(const Stmt &s) {
    if (const auto *b = dynamic_cast<const BlockStmt *>(&s)) return b->stmts.empty();
    return false;
  }

  // Evaluate expression and return a Python expression that holds the value.
  // If C semantics require side-effects (++, --, assignment-as-expression),
  // we lower them into statements and return a temp/variable name.
  std::string evalExpr(const Expr &e) {
    if (const auto *n = dynamic_cast<const NumberExpr *>(&e)) {
      return std::to_string(n->value);
    }
    if (const auto *v = dynamic_cast<const VarExpr *>(&e)) {
      return v->name;
    }
    if (const auto *u = dynamic_cast<const UnaryExpr *>(&e)) {
      if (u->op == UnOp::PreInc) {
        const auto *vv = dynamic_cast<const VarExpr *>(u->expr.get());
        if (!vv) throw std::runtime_error("PyGen: pre ++ requires variable");
        emitLine(vv->name + " += 1");
        return vv->name;
      }
      if (u->op == UnOp::PreDec) {
        const auto *vv = dynamic_cast<const VarExpr *>(u->expr.get());
        if (!vv) throw std::runtime_error("PyGen: pre -- requires variable");
        emitLine(vv->name + " -= 1");
        return vv->name;
      }
      const std::string x = evalExpr(*u->expr);
      const std::string t = freshTmp();
      if (u->op == UnOp::Neg) {
        emitLine(t + " = (-(" + x + "))");
        return t;
      }
      if (u->op == UnOp::Not) {
        emitLine(t + " = (0 if ((" + x + ") != 0) else 1)");
        return t;
      }
    }
    if (const auto *p = dynamic_cast<const PostfixExpr *>(&e)) {
      const auto *vv = dynamic_cast<const VarExpr *>(p->expr.get());
      if (!vv) throw std::runtime_error("PyGen: post ++/-- requires variable");
      const std::string t = freshTmp();
      emitLine(t + " = " + vv->name);
      if (p->op == PostOp::PostInc) emitLine(vv->name + " += 1");
      else if (p->op == PostOp::PostDec) emitLine(vv->name + " -= 1");
      return t;
    }
    if (const auto *b = dynamic_cast<const BinaryExpr *>(&e)) {
      if (b->op == BinOp::Assign) {
        const auto *lv = dynamic_cast<const VarExpr *>(b->lhs.get());
        if (!lv) throw std::runtime_error("PyGen: assignment LHS must be variable");
        std::string rhs = evalExpr(*b->rhs);
        emitLine(lv->name + " = " + rhs);
        return lv->name;
      }
      const std::string L = evalExpr(*b->lhs);
      const std::string R = evalExpr(*b->rhs);
      const std::string t = freshTmp();
      switch (b->op) {
        case BinOp::Add: emitLine(t + " = ((" + L + ") + (" + R + "))"); return t;
        case BinOp::Sub: emitLine(t + " = ((" + L + ") - (" + R + "))"); return t;
        case BinOp::Mul: emitLine(t + " = ((" + L + ") * (" + R + "))"); return t;
        case BinOp::Div: emitLine(t + " = ((" + L + ") // (" + R + "))"); return t;
        case BinOp::Mod: emitLine(t + " = ((" + L + ") % (" + R + "))"); return t;
        case BinOp::Lt:  emitLine(t + " = (1 if ((" + L + ") < (" + R + ")) else 0)"); return t;
        case BinOp::Le:  emitLine(t + " = (1 if ((" + L + ") <= (" + R + ")) else 0)"); return t;
        case BinOp::Gt:  emitLine(t + " = (1 if ((" + L + ") > (" + R + ")) else 0)"); return t;
        case BinOp::Ge:  emitLine(t + " = (1 if ((" + L + ") >= (" + R + ")) else 0)"); return t;
        case BinOp::Eq:  emitLine(t + " = (1 if ((" + L + ") == (" + R + ")) else 0)"); return t;
        case BinOp::Ne:  emitLine(t + " = (1 if ((" + L + ") != (" + R + ")) else 0)"); return t;
        case BinOp::And: emitLine(t + " = (1 if (((" + L + ") != 0) and ((" + R + ") != 0)) else 0)"); return t;
        case BinOp::Or:  emitLine(t + " = (1 if (((" + L + ") != 0) or ((" + R + ") != 0)) else 0)"); return t;
        case BinOp::Assign: break;
      }
    }
    throw std::runtime_error("PyGen: unknown expr node");
  }

  std::ostringstream out_;
  int indent_ = 0;
  std::int64_t tmpCounter_ = 0;
};

